### ISSUE TITLE
Support Python 3?

### ISSUE THREAD

**Issue by derekhh** [aws/sagemaker-tensorflow-extensions#15]
Is there a plan to support releasing a version that supports Python 3?

**Comment by owen-t** [comment]
Thanks for the suggestion. We're aware of this issue and see that it would be super-useful. We'll post back here when there is Python 3 support. Thanks!

**Comment by owen-t** [comment]
I'm rolling-out Python 3 support now. I've updated the master branch to add support for Python 3 for TF 1.9. This has also been built to PyPI. 

I'm working on changes for 1.7 and 1.8 and will comment here when they are released. 

I'll then update the README and do a changelog and version bump. 

Thanks!

**Comment by owen-t** [comment]
1.7 and 1.8 have been pushed to PyPI. We have support for 3.4, 3.5, 3.6 X TF 1.7, 1.8, 1.9.

I'm going to close this issue now. If you have any questions please reach out again. Thanks.

Owen.
