### ISSUE TITLE
Pip install only supports CPU tensorflow not GPU

### ISSUE THREAD

**Issue by MichaelX99** [aws/sagemaker-tensorflow-extensions#20]
Hello,

I am trying to install sagemaker_tensorflow to use pipemode however it uninstalls whatever tensorflow-gpu version I have and reinstalls the CPU version.  Is there a way to use pipe mode with a GPU tensorflow?

**Comment by MichaelX99** [comment]
A really bad way of fixing this was to install sagemaker-tensorflow, uninstall tensorflow, and reinstall tensorflow-gpu but this seems like a bad method... any suggestions?

**Comment by owen-t** [comment]
That's pretty bad behavior, thanks for pointing this out. I'm looking into this now. I'm considering removing the TF dependency entirely, [pip dependencies can't model this situation well](https://github.com/tensorflow/tensorflow/issues/7166) and anyone using this package probably has TensorFlow installed already.

**Comment by MichaelX99** [comment]
Removing it makes sense, at least to me.  At least all the documentation online has been pushing hard for our base Docker images to be tensorflow images so it should for 99.9% of the cases be installed already when we push our code to a training instance

**Comment by owen-t** [comment]
We've removed the explicit tensorflow dependency from the setup.py script. I've pushed the change to this GitHub repo and built to PyPI. 

Thanks for filing this issue. I'm going to close this now. 

Thanks,

Owen.
