### ISSUE TITLE
Out of range error with FIFO queue

### ISSUE THREAD

**Issue by MichaelX99** [aws/sagemaker-tensorflow-extensions#21]
Hello,

I recently kicked off 2 seperate training runs in Sagemaker using the PipeModeDataset and both recieved the following error at same number of training iterations:
`INFO:tensorflow:Caught OutOfRangeError. Stopping Training. FIFOQueue '_3_prefetch_queue' is closed and has insufficient elements (requested 1, current size 0)`

This was slightly over 10,000 steps in but am wondering what the cause of this could have been?  I am assuming it is the PipeModeDataset however I am not positive.  I will be starting the same experiments however using FileMode to see what is the culprit.

**Comment by owen-t** [comment]
Thanks for the info. I've not seen this error before - either using the PipeModeDataset or a standard Dataset. Please let us know if the error doesn't appear when you're using file mode. At that point, we'd probably want to see your code to help us reproduce, diagnose, and hopefully, fix the issue.

Thanks again,

Owen

**Comment by MichaelX99** [comment]
So unfortunately the code did not crash using Filemode and was able to make it past to 10k iteration point that Pipemode failed at.  Here is the relevant code which differentiates between File and Pipe mode:

    decoder = tf_example_decoder.TfExampleDecoder()

    def read_dataset(file_read_func, decode_func, input_files):
        filenames = tf.concat([tf.matching_files(pattern) for pattern in input_files], 0)
        filename_dataset = tf.data.Dataset.from_tensor_slices(filenames)
   
        filename_dataset = filename_dataset.repeat(num_epochs)
 
        records_dataset = filename_dataset.apply(
            tf.contrib.data.parallel_interleave(
            file_read_func, cycle_length=1,
            block_length=150, sloppy=True))
        tensor_dataset = records_dataset.map(
            decode_func, num_parallel_calls=16)
        return tensor_dataset.prefetch(prefetch_size)

     def process_fn(value):
         processed = decoder.decode(value)
         return processed
 
     if pipemode_channel == 'File':
         dataset = dataset_util.read_dataset(
             functools.partial(tf.data.TFRecordDataset, buffer_size=8 * 1000 * 1000),
             process_fn, input_path)
 
     elif pipemode_channel == 'Train':
         dataset = PipeModeDataset(channel='train', record_format='TFRecord')
         dataset = dataset.map(
             process_fn,
             num_parallel_calls=16)
         dataset = dataset.prefetch(prefetch_size)
 
     elif pipemode_channel == 'Eval':
         dataset = PipeModeDataset(channel='eval', record_format='TFRecord')
         dataset = dataset.map(
             process_fn,
             num_parallel_calls=16)
         dataset = dataset.prefetch(prefetch_size)
 
 
     return dataset

**Comment by owen-t** [comment]
Hi Michael,

I've reached out to you via email to request some additional info to help me resolve this issue.

Regards,

Owen.

**Comment by owen-t** [comment]
Hi Michael,

I'm going to resolve this issue. If you could respond to my email then I can help you debug this issue further. If you'd like me to provide the email again, please let me know.

Regards,

Owen.
