### ISSUE TITLE
PipeModeDatasetError

### ISSUE THREAD

**Issue by gdj0nes** [aws/sagemaker-tensorflow-extensions#27]
I'm getting this error when trying to run pipemode on TF 1.11.0 in local mode.
```
algo-1-TA50U_1  |   File "/usr/local/lib/python2.7/dist-packages/sagemaker_tensorflow/pipemode.py", line 65, in __init__
algo-1-TA50U_1  |     self._require_pipemode()
algo-1-TA50U_1  |   File "/usr/local/lib/python2.7/dist-packages/sagemaker_tensorflow/pipemode.py", line 74, in _require_pipemode
algo-1-TA50U_1  |     raise PipeModeDatasetException("PipeModeDataset must be used with SageMaker Pipe Mode, not File Mode.")
algo-1-TA50U_1  | PipeModeDatasetException: PipeModeDataset must be used with SageMaker Pipe Mode, not File Mode.
```
I'm running the model with `TensorFlow(role=role, framework_version='1.11.0', input_mode='Pipe', **sm_params)`

**Comment by gdj0nes** [comment]
Ok I found out that the channel need to be named 'training'. Could this be documented better?

**Comment by owen-t** [comment]
Yes, sorry for the confusion. We will leave this open until the documentation is corrected.

Thanks again for your feedback, it's really useful.
