### ISSUE TITLE
Problems Reading AugmentedManifest Mode Pipe

### ISSUE THREAD

**Issue by canada4663** [aws/sagemaker-tensorflow-extensions#33]
Hello  - 

My understanding from your [documentation on AugmentedManifest file mode](https://docs.aws.amazon.com/sagemaker/latest/dg/augmented-manifest.html)  is that each 'Attribute' is wrapped by a recordIO wrapper.  In my case, it should follow the example from the docs:

```
recordio_formatted(s3://mybucket/foo/image1.jpg)recordio_formatted("1")recordio_formatted(s3:......
```

I *mostly* confirmed this by essentially recording the piped FIFO data to disk with minor modification to the[ pipe mode example notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/d496eccc3bf09dae8c02e82e617046fd61f51d84/advanced_functionality/pipe_bring_your_own/pipe_bring_your_own.ipynb).

When I use PipeModeDataSet to read this file similar to how the tests do, I am *sometimes* able to do the below and get clean samples:

```
def _input_fn(): 
    def parseRecord(record):
        return tf.convert_to_tensor(record[0], dtype=tf.string), tf.convert_to_tensor(record[1], dtype=tf.string)

    ds = PipeModeDataset(channel, pipe_dir=directory, state_dir=directory, config_dir=directory, benchmark=True)
    ds = ds.batch(2)
    ds = ds.map(parseRecord)
    ds = ds.batch(5)
    return ds

with tf.Session() as sess:
    it = _input_fn().make_one_shot_iterator()
    next = it.get_next()
    mini_batch = sess.run(next)

image, label = mini_batch

#validate image is 5 images, label is 5 corresponding labels
```

My conclusion here is that the protocol DOES follow the documentation and interleave records alternating image and label.  

The challenge here is that this approach doesn't always work.  Couple of places it fails:
1) anytime I try to do any parallel calls (using map or map and batch) in other parts of processing pipeline, including larger batch size after initial ```ds.batch(2)``` call.   I get errors such as:
```
Index out of range using input dim 0; input has only 0 dims for 'strided_slice' (op: 'StridedSlice') with input shapes: [], [1], [1], [1] and with computed input tensors: input[3] = <1>.
```
```
Multipart records are not supported
```

2) when I run it in a container in SageMaker streaming actual AugmentedManifest file data (as opposed to replaying recorded data).  In these situations I get errors such as:

```
tensorflow.python.framework.errors_impl.InternalError: Invalid magic number: 524330
```
```
#011 [[{{node IteratorGetNext_3}} = IteratorGetNext[output_shapes=[[?], [?]], output_types=[DT_STRING, DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator)]]
```

I reviewed the tests and I don't see any test cases for reading the PIPE input from an AugmentedManifest based training job, and all of the test cases involving TensorFlow seem to entail RecordIO wrapping TFRecord data (hence the deinterleaving AugmentedManifest forced you to deal with isn't requiredas TFRecord has the features and labels in same record).

I'm still trying a number of things, and perhaps its naivette around tf.data pipeline capability (.... still trying window, shard, and interleave as workarounds).  I also can't seem to understand why the ```ds.batch(2)``` call followed by a map to parse that 'tuple' doesn't work - nearest I can imagine is that parallel processing and prefetching doesn't guarantee order in the pipeline, and dimensions change depending on the batch.

All that said, would LOVE LOVE to see a) a clear example of how to use PipeModeDataset in TensorFlow and Keras to read AugmentedManifest PIPE mode data, and / or b) enhancements to PipeModeDataset to read two records at a time from PIPE FIFO and wrap them in TFRecord features that TF can natively understand.

**Comment by owen-t** [comment]
Hi,

Thanks for the really detailed issue. 

The PipeModeDataset does not directly support the Augmented Manifest format. It's designed to be used with S3 Prefix and Manifest formats. 

I feel that the correct fix is to do something along the lines of (b) - let's make a Dataset implementation that plays nicely with the Augmented Manifest format.

I don't yet have an answer for why ds.batch didn't work as expected. This will require some investigation.

Thanks,

Owen.

**Comment by owen-t** [comment]
I'd like to understand more about the data you are training with and your training script. 

1. Could you please share the scripts that are generating these problems. It looks like you're running the PipeModeDataset yourself, locally - using an approach like I did in the functional tests. It also looks like you're running on SageMaker itself. I'd love to see both of these scripts, if possible.

2. Could you please share the API call you use to launch Training on SageMaker. If you're using the SageMaker Python SDK to launch training, could you share the script that you use to launch training. 

3. Could you please share the data - or a description of the data - you're training with.

It's not clear from the information you shared, you may already be doing this: Make sure you set the RecordWrapperType to RecordIO when you launch SageMaker training.

If you're not happy sharing this information publicly, I can provide a method for communicating privately.

Thanks,

Owen.

**Comment by owen-t** [comment]
I spoke with the OP via email and have updated the Readme to include a guide on using the PipeModeDataset with the SageMaker Augmented Manifest File.
