### ISSUE TITLE
Support Tensorflow 2

### ISSUE THREAD

**Issue by cnliusen** [aws/sagemaker-tensorflow-extensions#56]
Is there a plan to support tensorflow 2?  When I try to import `sagemaker_tensorflow` I got this error:

```
algo-1-7a79s_1  | Traceback (most recent call last):
algo-1-7a79s_1  |   File "train.py", line 14, in <module>
algo-1-7a79s_1  |     import sagemaker_tensorflow
algo-1-7a79s_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow/__init__.py", line 15, in <module>
algo-1-7a79s_1  |     from sagemaker_tensorflow.pipemode import PipeModeDataset, PipeModeDatasetException
algo-1-7a79s_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow/pipemode.py", line 37, in <module>
algo-1-7a79s_1  |     class PipeModeDataset(dataset_ops.Dataset):
algo-1-7a79s_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow/pipemode.py", line 40, in PipeModeDataset
algo-1-7a79s_1  |     _tf_plugin = _load_plugin()
algo-1-7a79s_1  |   File "/usr/local/lib/python3.6/dist-packages/sagemaker_tensorflow/pipemode.py", line 28, in _load_plugin
algo-1-7a79s_1  |     return tf.load_op_library(tf_plugin_path)
algo-1-7a79s_1  |   File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
algo-1-7a79s_1  |     lib_handle = py_tf.TF_LoadLibrary(library_filename)
algo-1-7a79s_1  | tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.1: cannot open shared object file: No such file or directory
algo-1-7a79s_1  | 2019-11-07 00:54:50,473 sagemaker-containers ERROR    ExecuteUserScriptError:
algo-1-7a79s_1  | Command "/usr/bin/python3 train.py"
```

**Comment by nadiaya** [comment]
Hi,

Thank you for using SageMaker. We do have tensorflow 2 support on our roadmap in the near future.

**Comment by laurenyu** [comment]
related: https://github.com/aws/sagemaker-tensorflow-container/issues/246

**Comment by nadiaya** [comment]
Keeping it open until we release the support for TF 2.0

**Comment by 00krishna** [comment]
@nadiaya are you able to indicate when a TF 2.0 container will be released? Meaning, is the container in testing phase, or is it just being reviewed, etc? I was just wondering since otherwise I need to either build a custom container, or I have to choose to just build some EC2 nodes using a TF 2.0 docker container. So once I pick a direction it gets hard to switch over mid-stream. Like even if you can say that it is likely a week, versus a few weeks versus a couple months, that is fine.

**Comment by 00krishna** [comment]
I thought I would check if there are any updates to Tensorflow 2.0 availability in advance of the AWS conference next week? Are they planning any new releases of the containers? Thanks.

**Comment by 00krishna** [comment]
I thought I would check if there are any updates to Tensorflow 2.0 availability in advance of the AWS conference next week? Are they planning any new releases of the containers? Thanks.

**Comment by Chipzstar** [comment]
Any news on the tensorflow 2.0 containers??? Any update on its status would be really appreciated!

**Comment by nadiaya** [comment]
Pipe mode support for tensorflow 2.0 has been released last week:

https://pypi.org/project/sagemaker-tensorflow/2.0.0.1.0.0/

**Comment by athewsey** [comment]
@nadiaya both the current `master/README.rst` and the page you linked start the description with:

> SageMaker specific extensions to TensorFlow, for Python 2.7, 3.4-3.6 and TensorFlow versions 1.7-1.12

I've not tried TF v2, but my experience on #46 certainly made it seem like 1.13 isn't supported yet... Could the docs be updated to say what v2 support is available? Thanks!
